### ISSUE TITLE
What module is the one referenced in the release notes for the latest version?

### ISSUE THREAD

**Issue by solarflair** [theripper93/quick-grid-align#2]
I see it says "Locked to V11, module has been deprecated. The module this was supposed to replace has been revived"

But I see no mention anywhere in the documentation what module this is referring to, and when searching modules for keywords such as "grid" I don't see anything with updates in the last few months.

What module was quick-grid-align intended to replace that has resumed development for v12?

**Comment by theripper93** [comment]
Background scaler
